### PR TITLE
Add a new "round" option parameter

### PR DESCRIPTION
**Pull request by Pipo31416**
I propose to update the relative_time_plus macro with a new parameter "round" to output the result to the upper value.
Example:
 if the output of {{ relative_time_plus(date,3) }} is "3 hours , 2 minutes and 30 seconds"
 then the output of {{ relative_time_plus(date,2) }} will be "3 hours  and 3 minutes".

Maybe the code is a bit hard to understand because it avoid all results like "1 minute and 60 seconds" or "1 week and 7 days".
Tell me if you can simplify it.
Thanks

### CODE REVIEW

**Comment by TheFes** [comment]
I'll have a look at the actual code to round later today or tomorrow

**Comment by Pipo31416** [comment]
Thanks

Two additional explanations:
1) The first loop compute the new value of time_parts[last] (ns.n).
2) The second loop populate time_parts with the new value ns.n and propagate the eventual carry from [last] to [first].
Hope this could help. I forgot to add these comments in the code.

**Comment by TheFes** [comment]
I like the idea of adding a round parameter, but I think it makes more sense to add it to the `time_parts` submacro.

I've also changed it to `round_mode`
It takes the parameters `"floor"`, `"ceil"` and `"common"`

Could you have a look at the version in this branch
https://github.com/TheFes/relative-time-plus/tree/version_1.4.0

**Comment by TheFes** [comment]
Ah wait, I see I did not take your comment into account with the 59 > 60 seconds. I'll look into that:
image

**Comment by TheFes** [comment]
fixed
image

**Comment by Pipo31416** [comment]
I have some diffs with the result of my tests. Here here the macro used:

{%- set date  = '2023-01-16T14:00:00+01:00' -%}
{%- set date0 = '2024-03-18T15:30:59.5+01:00' -%}
{% for i in range(1,9) %}
{{ i }}
{{ relative_time_plus(date,i,compare_date=date0,language='fr',week=false) }}
{{ relative_time_plus(date,i,compare_date=date0,language='fr',week=true,round_mode=ceil) }}
{{ relative_time_plus(date,i,compare_date=date0,language='fr',month=false,round_mode=ceil) }}
{{ relative_time_plus(date,i,compare_date=date0,language='fr',month=false,round_mode=ceil) }}
{{ relative_time_plus(date,i,compare_date=date0,language='fr',not_use=['year','week'],round_mode=ceil) }}
{% endfor %}

Not that I wrote my round code in the relative_time_plus macro juste before the phrases code to use the final "do_use" list.
It's not the case now since you move it in the macro time_split.
So now the week (in the example above) appear even if was not asked!

Another thing: when I change date0 to: 
{%- set date0 = '2023-03-18T15:30:59.5+01:00' -%}
The result is: UndefinedError: 'yrs' is undefined

**Comment by Pipo31416** [comment]
I found some diffs with my test script:
```
{%- set date  = '2023-01-16T14:00:00+01:00' -%}
{%- set date0 = '2024-03-18T15:30:59.5+01:00' -%}
{% for i in range(1,9) %}
{{ i }}
{{ relative_time_plus(date,i,compare_date=date0,language='fr',week=false) }}
{{ relative_time_plus(date,i,compare_date=date0,language='fr',week=true,round_mode='ceil') }}
{{ relative_time_plus(date,i,compare_date=date0,language='fr',month=false,round_mode='ceil') }}
{{ relative_time_plus(date,i,compare_date=date0,language='fr',month=false,week=false,always_show=['milliseconds'],round_mode='ceil') }}
{{ relative_time_plus(date,i,compare_date=date0,language='fr',not_use=['year','week'],round_mode='ceil') }}
{% endfor %}
```
It seems that too much values are rounded that the `parts `parameter asked.

Also, when I use:
`
{%- set date0 = '2023-03-18T15:30:59.5+01:00' -%}
`
I get an error: **yrs is not defined**

**Comment by Pipo31416** [comment]
I spent over an hour properly testing your code before understood my error, and I edited the last post a lot!
I definitly hate "ceil" and "floor"which I always confuse. I only use "round" or +0.5 !
But I respect your choice :)

**Comment by TheFes** [comment]
I'll have another look when I'm less tired

**Comment by TheFes** [comment]
I made a lot of changes
* moved all the logic to the `time_split` macro.
* removed the `week`, `month` and `millisecond` parameters, as they can be set use `not_use`
* removed the `verbose` parameter, as it was doing the opposite and replaced by the `abbr` parameter a long time ago
* added another macro to do the conversion of abbreviated lists for `not_use` and `always_show` to the full time part names
* for making sure all items in `always_show` are used, and for the the rounding the `time_split` macro calls itself again.

I used the code below for testing (the datetime strings are taken from your tests above). Note that when a time part retruns `0` it will not be shown in the output, unless it is listed in `always_show`. As your datetimes resulted in `0 weeks` this causes that the number of parts shown doesn't match the number of parts requested in many cases.
Also because it shows `59 seconds` that will change to `0 seconds` when rounded, so that also will cause the seconds not to be returned.

```jinja2
{% from 'relative_time_plus.jinja' import time_split, relative_time_plus %}

{% set d, cd = '2023-01-16T14:00:00+01:00', '2024-03-18T15:30:59.5+01:00' %}
{{ time_split(d, 8, cd, [], 'all') }}

{% for i in range(1,9) %}
parts: {{ i }}
{{ relative_time_plus(d, i, compare_date=cd) }}
{{ relative_time_plus(d, i, compare_date=cd, round_mode='common') }}
{{ relative_time_plus(d, i, compare_date=cd, round_mode='ceil') }}
{{ relative_time_plus(d, i, compare_date=cd, not_use=['week', 'month'], round_mode='ceil') }}
{{ relative_time_plus(d, i, compare_date=cd, not_use=['week'], always_show=['day'], round_mode='ceil') }} 
{% endfor %}
```

This is the output:
```
{"year":1,"month":2,"week":0,"day":2,"hour":1,"minute":30,"second":59,"millisecond":500}


parts: 1
1 year
1 year
2 years
2 years
428 days 

parts: 2
1 year and 2 months
1 year and 2 months
1 year and 3 months
1 year and 62 days
1 year and 62 days 

parts: 3
1 year and 2 months
1 year and 2 months
1 year, 2 months and 1 week
1 year, 61 days and 2 hours
1 year, 2 months and 3 days 

parts: 4
1 year, 2 months and 2 days
1 year, 2 months and 2 days
1 year, 2 months and 3 days
1 year, 61 days, 1 hour and 31 minutes
1 year, 2 months, 2 days and 2 hours 

parts: 5
1 year, 2 months, 2 days and 1 hour
1 year, 2 months, 2 days and 2 hours
1 year, 2 months, 2 days and 2 hours
1 year, 61 days, 1 hour and 31 minutes
1 year, 2 months, 2 days, 1 hour and 31 minutes 

parts: 6
1 year, 2 months, 2 days, 1 hour and 30 minutes
1 year, 2 months, 2 days, 1 hour and 31 minutes
1 year, 2 months, 2 days, 1 hour and 31 minutes
1 year, 61 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds
1 year, 2 months, 2 days, 1 hour and 31 minutes 

parts: 7
1 year, 2 months, 2 days, 1 hour, 30 minutes and 59 seconds
1 year, 2 months, 2 days, 1 hour, 30 minutes and 59 seconds
1 year, 2 months, 2 days, 1 hour, 30 minutes and 59 seconds
1 year, 61 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds
1 year, 2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds 

parts: 8
1 year, 2 months, 2 days, 1 hour, 30 minutes and 59 seconds
1 year, 2 months, 2 days, 1 hour, 30 minutes and 59 seconds
1 year, 2 months, 2 days, 1 hour, 30 minutes and 59 seconds
1 year, 61 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds
1 year, 2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds
```

**Comment by Pipo31416** [comment]
Ok for your example.
But when I change the year of `cd` to 2023 (with all round_mode to 'common'):
```
{% from 'relative_time_plus_v1.4B.jinja' import time_split, relative_time_plus %}
{% set d, cd = '2023-01-16T14:00:00+01:00', '2023-03-18T15:30:59.5+01:00' %}
{% set rm = 'common' %}
{{ time_split(d, 8, cd, [], 'all') }}
{% for i in range(1,9) %}
parts: {{ i }}
{{ relative_time_plus(d, i, compare_date=cd) }}
{{ relative_time_plus(d, i, compare_date=cd, round_mode=rm) }}
{{ relative_time_plus(d, i, compare_date=cd, not_use=['week', 'month'], round_mode=rm) }}
{{ relative_time_plus(d, i, compare_date=cd, not_use=['week'], round_mode=rm) }} 
{#- relative_time_plus(d, i, compare_date=cd, not_use=['week'], always_show=['day'], round_mode=rm) }}{#- <- TypeError: Dict key must a type serializable with OPT_NON_STR_KEYS #} 
{% endfor %}
```
I got an error with `always_show=['day']`
and the result is strange:
```
{"year":0,"month":2,"week":0,"day":2,"hour":1,"minute":30,"second":59,"millisecond":500}

parts: 1
2 months
2 months
2 hours
2 months 

parts: 2
2 months
2 months
1 hour and 31 minutes
2 months and 2 days 

parts: 3
2 months and 2 days
2 months and 2 days
1 hour, 30 minutes and 59 seconds
2 months, 2 days and 2 hours 

parts: 4
2 months, 2 days and 1 hour
2 months, 2 days and 2 hours
1 hour, 30 minutes, 59 seconds and 500 milliseconds
2 months, 2 days, 1 hour and 31 minutes 

parts: 5
2 months, 2 days, 1 hour and 30 minutes
2 months, 2 days, 1 hour and 31 minutes
1 hour, 30 minutes, 59 seconds and 500 milliseconds
2 months, 2 days, 1 hour, 30 minutes and 59 seconds 

parts: 6
2 months, 2 days, 1 hour, 30 minutes and 59 seconds
2 months, 2 days, 1 hour, 30 minutes and 59 seconds
1 hour, 30 minutes, 59 seconds and 500 milliseconds
2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds 

parts: 7
2 months, 2 days, 1 hour, 30 minutes and 59 seconds
2 months, 2 days, 1 hour, 30 minutes and 59 seconds
1 hour, 30 minutes, 59 seconds and 500 milliseconds
2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds 

parts: 8
2 months, 2 days, 1 hour, 30 minutes and 59 seconds
2 months, 2 days, 1 hour, 30 minutes and 59 seconds
1 hour, 30 minutes, 59 seconds and 500 milliseconds
2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds
```

**Comment by TheFes** [comment]
great find, should have tested a timedelta without years myself.

**Comment by TheFes** [comment]
fixed the strange results and the TypeError (which were both caused by the same thing)

**Comment by Pipo31416** [comment]
Ok, that's fixed.
But IMHO, in the above examples,  the results "` and 59 seconds`" are erroneous whith `round_mode='common'`.
Otherwise, I didn't found other issues :)
Thanks

**Comment by TheFes** [comment]
There seems to be a bug in the round filter/function

`{{ 0.5 | round(0, 'common') }}` returns `0`

I've worked around that using
`{%- set to_round = 1 if remain_part >= 0.5 and round_mode == 'common' else remain_part | round(0, round_mode) -%}`

eg: parts 5
before:
```
2 months, 2 days, 1 hour, 30 minutes and 59 seconds 
```
after:
```
2 months, 2 days, 1 hour and 31 minutes 
```

So now it rounds properly:
```
{"year":0,"month":2,"week":0,"day":2,"hour":1,"minute":30,"second":59,"millisecond":500}

parts: 1 
2 months
2 months
61 days
2 months 
61 days

parts: 2 
2 months
2 months
61 days and 2 hours
2 months and 2 days 
2 months and 2 days

parts: 3 
2 months and 2 days
2 months and 2 days
61 days, 1 hour and 31 minutes
2 months, 2 days and 2 hours 
2 months, 2 days and 2 hours

parts: 4 
2 months, 2 days and 1 hour
2 months, 2 days and 2 hours
61 days, 1 hour and 31 minutes
2 months, 2 days, 1 hour and 31 minutes 
2 months, 2 days, 1 hour and 31 minutes

parts: 5 
2 months, 2 days, 1 hour and 30 minutes
2 months, 2 days, 1 hour and 31 minutes
61 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds
2 months, 2 days, 1 hour and 31 minutes 
2 months, 2 days, 1 hour and 31 minutes

parts: 6 
2 months, 2 days, 1 hour, 30 minutes and 59 seconds
2 months, 2 days, 1 hour, 30 minutes and 59 seconds
61 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds
2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds 
2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds

parts: 7 
2 months, 2 days, 1 hour, 30 minutes and 59 seconds
2 months, 2 days, 1 hour, 30 minutes and 59 seconds
61 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds
2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds 
2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds

parts: 8 
2 months, 2 days, 1 hour, 30 minutes and 59 seconds
2 months, 2 days, 1 hour, 30 minutes and 59 seconds
61 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds
2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds 
2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds
```

**Comment by Pipo31416** [comment]
Good !
But I don't understand why it's not the same result with parts 6, 7 and 8 (second line) ?
I missed something ?

**Comment by TheFes** [comment]
It's not a bug BTW, jinja uses even rounding, so 0.5 is rounded to `0` (the nearest even number), same as `2.5` will be rounded to `2`

For the other ones:
```
parts: 6 
2 months, 2 days, 1 hour, 30 minutes and 59 seconds > no round option applied (so `floor` is used)
2 months, 2 days, 1 hour, 30 minutes and 59 seconds > by default milliseconds are in the `not_use` list, so they are not used
61 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds > because months and weeks are not used milliseconds is the 6th part
2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds > same as above
2 months, 2 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds > same as above
```

```
{{ relative_time_plus(d, 6, compare_date=cd, round_mode=rm, not_use=[]) }}
```
returns: `2 months, 2 weeks, 2 days, 1 hour and 31 minutes` so then it does round.

Would you expect it to round even though it's in the `not_use` list? I can have a look at that.

**Comment by Pipo31416** [comment]
Ok, my misunderstanding concerned the `not_use` parameter which I confused with a `not_show` parameter.
 I thought that all time parts were always used to calculate the result.
Perhaps it woult be better to use all time parts when `round_mode` is defined...

**Comment by TheFes** [comment]
Yes, I agree, I'll add that.

**Comment by Pipo31416** [comment]
For me: `2 years and 3 months` -> 2.25 yr -> `2 years`, not `3 years` with round common mode...
Not for you?

**Comment by TheFes** [comment]
hehe, good that someone is paying attention.. 
Thanks for all the checking BTW! I keep breaking stuff when I'm fixing other things :)

**Comment by TheFes** [comment]
input:
```
{% from 'relative_time_plus.jinja' import time_split, relative_time_plus %}
{% set d, cd = '2021-01-02T14:00:00+01:00', '2023-03-18T15:30:59.5+01:00' %}
{% set rm = 'common' %}
{{ time_split(d, 8, cd, [], 'all') }}
{% for i in range(1,9) %}
parts: {{ i }}
  {{ relative_time_plus(d, i, compare_date=cd) }} # floor
  {{ relative_time_plus(d, i, compare_date=cd, round_mode=rm) }} # common
  {{ relative_time_plus(d, i, compare_date=cd, round_mode='ceil') }} # ceil
  {{ relative_time_plus(d, i, compare_date=cd, not_use=['week', 'month'], round_mode=rm) }} # common, reject week and month
  {{ relative_time_plus(d, i, compare_date=cd, not_use=['week'], round_mode=rm) }} # common, reject week
  {{ relative_time_plus(d, i, compare_date=cd, not_use=['week'], always_show=['day'], round_mode=rm) }} # common, reject week, always show day
{% endfor %}   
```

ouput:
```
{"year":2,"month":2,"week":2,"day":2,"hour":1,"minute":30,"second":59,"millisecond":500}

parts: 1
  2 years # floor
  2 years # common
  3 years # ceil
  2 years # common, reject week and month
  2 years # common, reject week
  805 days # common, reject week, always show day

parts: 2
  2 years and 2 months # floor
  2 years and 3 months # common
  2 years and 3 months # ceil
  2 years and 75 days # common, reject week and month
  2 years and 3 months # common, reject week
  2 years and 91 days # common, reject week, always show day

parts: 3
  2 years, 2 months and 2 weeks # floor
  2 years, 2 months and 2 weeks # common
  2 years, 2 months and 3 weeks # ceil
  2 years, 75 days and 2 hours # common, reject week and month
  2 years, 2 months and 16 days # common, reject week
  2 years, 2 months and 16 days # common, reject week, always show day

parts: 4
  2 years, 2 months, 2 weeks and 2 days # floor
  2 years, 2 months, 2 weeks and 2 days # common
  2 years, 2 months, 2 weeks and 3 days # ceil
  2 years, 75 days, 1 hour and 31 minutes # common, reject week and month
  2 years, 2 months, 16 days and 2 hours # common, reject week
  2 years, 2 months, 16 days and 2 hours # common, reject week, always show day

parts: 5
  2 years, 2 months, 2 weeks, 2 days and 1 hour # floor
  2 years, 2 months, 2 weeks, 2 days and 2 hours # common
  2 years, 2 months, 2 weeks, 2 days and 2 hours # ceil
  2 years, 75 days, 1 hour and 31 minutes # common, reject week and month
  2 years, 2 months, 16 days, 1 hour and 31 minutes # common, reject week
  2 years, 2 months, 16 days, 1 hour and 31 minutes # common, reject week, always show day

parts: 6
  2 years, 2 months, 2 weeks, 2 days, 1 hour and 30 minutes # floor
  2 years, 2 months, 2 weeks, 2 days, 1 hour and 31 minutes # common
  2 years, 2 months, 2 weeks, 2 days, 1 hour and 31 minutes # ceil
  2 years, 75 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds # common, reject week and month
  2 years, 2 months, 16 days, 1 hour and 31 minutes # common, reject week
  2 years, 2 months, 16 days, 1 hour and 31 minutes # common, reject week, always show day

parts: 7
  2 years, 2 months, 2 weeks, 2 days, 1 hour, 30 minutes and 59 seconds # floor
  2 years, 2 months, 2 weeks, 2 days, 1 hour and 31 minutes # common
  2 years, 2 months, 2 weeks, 2 days, 1 hour and 31 minutes # ceil
  2 years, 75 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds # common, reject week and month
  2 years, 2 months, 16 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds # common, reject week
  2 years, 2 months, 16 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds # common, reject week, always show day

parts: 8
  2 years, 2 months, 2 weeks, 2 days, 1 hour, 30 minutes and 59 seconds # floor
  2 years, 2 months, 2 weeks, 2 days, 1 hour and 31 minutes # common
  2 years, 2 months, 2 weeks, 2 days, 1 hour and 31 minutes # ceil
  2 years, 75 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds # common, reject week and month
  2 years, 2 months, 16 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds # common, reject week
  2 years, 2 months, 16 days, 1 hour, 30 minutes, 59 seconds and 500 milliseconds # common, reject week, always show day
  ```

**Comment by TheFes** [comment]
Implemented otherwise in #40 

Thanks for the suggestion and all the testing!

**Comment by TheFes** [comment]
Implemented otherwise in https://github.com/TheFes/relative-time-plus/pull/40

Thanks for the suggestion and all the testing!

**Pull request closed without merging**
