### PR TITLE
Add Spanish to supported language list 

### PR DESCRIPTION
**Pull request by cvc90**
Hi @TheFes, 

this PR is sent with the translation to the Spanish language.

### CODE REVIEW

**Comment by TheFes** [comment]
Thanks for adding Spanish, however while you submitted this PR I was reviewing another PR which makes changes to the the way the translations are provided.

For Spanish this only means the abbreviated form has to be first in the list instead of last. Can you change this?

**Comment by TheFes** [comment]
I forgot to mention you also need to add `'plural_form': 'english',` (see for example the English translation below yours).

**Comment by cvc90** [comment]
@TheFes, Can you please check it again?

**Comment by TheFes** [comment]
You need to put the abbreviated form first now, so instead:
`'year': ['año', 'años', 'a'],`
it needs to be
`'year': ['a', 'año', 'años'],`

**Comment by cvc90** [comment]
It is already corrected :+1:

**Review by TheFes — APPROVED** [review]
Looks good

**Comment by TheFes** [comment]
Thanks!

**Comment by cvc90** [comment]
When will you update the release with these changes?

**Comment by TheFes** [comment]
In a few minutes :)

**Comment by cvc90** [comment]
Thanks! 😄

**Comment by TheFes** [comment]
https://github.com/TheFes/relative-time-plus/releases/tag/v2.3.0

**Pull request merged**
